#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server
if [ "$#" -ne 4 ]; then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key="$4"

scp_command="scp -o StrictHostKeyChecking=no"

if [ -n "$ssh_key" ]; then
    $scp_command -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
else
    $scp_command "$file_path" "$username@$server_ip:~/"
fi
