#!/usr/bin/env bash

# Update package list and install nginx with the -y flag for non-interactive installation

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null

sudo cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;
}
EOF

sudo service nginx restart
