#!/usr/bin/env bash
# Update package list and install nginx with the -y flag for non-interactive installation

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

sudo cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
}
EOF

sudo service nginx restart
