#!/usr/bin/env bash
# Install Nginx on an Ubuntu web server

echo "Installing Nginx..."
sudo apt-get update -y
sudo apt-get install -y nginx

# Getting the hostname
hostname=$(hostname)

# Configure Nginx
echo "Configuring Nginx..."
sudo cat <<EOF | sudo tee /etc/nginx/sites-available/default > /dev/null
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm;

    server_name _;

    location / {
        return 200 "Hello World!\\n";
    }

    # Custom HTTP response header with the actual hostname
    add_header X-Served-By $hostname;
}
EOF

# Restart Nginx
echo "Restarting Nginx..."
sudo service nginx restart

echo "Nginx installation and configuration completed!"
