#!/usr/bin/env bash
# Check if an IP address is provided as an argument

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

if [[ ! "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid IP address format: $1"
  exit 1
fi

ping -c 5 "$1"
