#!/usr/bin/env bash
# Function to check if an argument is a valid IP address

is_valid_ip() {
  local ip="$1"
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    return 0
  else
    return 1
  fi
}

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

if is_valid_ip "$1"; then
  ping -c 5 "$1"
else
  echo "Invalid IP address format: $1"
  exit 1
fi
