#!/usr/bin/env bash
# Check if the number of arguments is less than 1

if [ "$#" -lt 1 ]; then
  echo "Usage: $0 {IP_ADDRESS}"
  exit 1
fi

if [[ ! "$1" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  echo "Invalid IP address format: $1"
  exit 1
fi

ping -c 5 "$1"
