#!/usr/bin/env bash
#This configures nginx to listen on port 80

l="/etc/nginx/sites-enabled/default"
t="/etc/nginx/sites-available/default"
sudo rm -f "$l" && sudo ln -s "$t" "$l" && sudo service nginx restart
