#!/usr/bin/env bash
#displays the content of the file /etc/passwd
myfile="/etc/passwd"

while IFS=: read -r uname _ uid gid desc home shell
do
    echo "The user $uname is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $desc, more info about the user here: $uid"
done < "$myfile"
