#!/usr/bin/env bash
# Initialize a counter variable

count=1

while [ $count -le 10 ]
do
    if [ $count -eq 4 ]; then
        echo "bad luck"
    else
        if [ $count -eq 8 ]; then
            echo "good luck"
        else
            echo "Best School"
        fi
    fi
    
    ((count++))
done
