#!/usr/bin/env bash
# Define the new hosts file content

new_hosts_content=$(cat <<EOL
127.0.0.2 localhost
8.8.8.8 facebook.com
EOL
)

if [ -f "/.dockerenv" ]; then

  sudo cp /etc/hosts /etc/hosts.bak

  echo "$new_hosts_content" | sudo tee /etc/hosts > /dev/null

  echo "Configuration complete."
else
  echo "This script should be run inside a Docker container."
fi
