#!/usr/bin/env bash
# Fixes a web server to run Nginx as the nginx user listening on port 8080.
[ "$EUID" -ne 0 ] && { echo "Please run this script as root or using sudo."; exit 1; }
pkill apache2; sed -i 's/80/8080/g' /etc/nginx/sites-enabled/default
chown -R nginx:nginx /etc/nginx/ && chmod -R 700 /etc/nginx/
sudo -u nginx service nginx restart
echo "Nginx is now configured to run as nginx user and listening on port 8080."
